services:
  api:
    build:
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    env_file:
    - ./src/common/envs/development.env
    # Run a command against the development stage of the image
    command: yarn run start:dev
    ports:
      - 1938:1938
